config/routes.rb
Ikefuji::Application.routes.draw do

  devise_for :users

  resources :dictionaries do 
    member do 
      get :evaluate
      get :auto_evaluate
      get :julius_evaluate
      get :julius_auto_evaluate
    end
    resources :recog_processes do 
      member do 
        get :status
        get :register
        get :start
        get :stop
        get :unregister
      end
    end
    resources :expressions
  end

  resources :readings
  resources :word_groups
  resources :words

  root :to => 'dictionaries#index'

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  include GrammarStyle
  include Rate

  attr_accessible :name, :grammar_style, :rate, 
  :dictionary_members_attributes

  #### associations ####
  belongs_to :user
  has_many :words
  has_many :dictionary_members
  has_many :word_groups, through: :dictionary_members, order: :position
  has_many :recog_processes
  has_many :expressions
  
  accepts_nested_attributes_for :dictionary_members, allow_destroy: true

  #### validations ####
  validates :name, presence: true
  validates :grammar_style, :inclusion => { 
    :in => [ GRAMMAR_FREE, GRAMMAR_FIXED ] }
  validates :rate, :inclusion => { 
    :in => [ 8, 16 ] }


=begin
  def make_voca_grammar
    path = Rails.root.to_s + "/tmp/" + dir_name
    if !File.exists? path
      Dir::mkdir path
    end
    # p File.exists? path

    ## for Fixed style grammer rules
    ## create a .voca file
    voca_path = path + "/#{dir_name}.voca"
    voca = File.open voca_path, "w+"
    voca.write "% #{dir_name}\n"

    ## for Free style grammer rules
    ## create a .txt file (dictionary file)
    txt_path = path + "/#{dir_name}.txt"
    txt = File.open txt_path, "w+"
    txt.write "</s>    []      silE\n"
    txt.write "<s>     []      silB\n"
    
    words.each do |w|
      w.readings.each do |r|
        voca.write "#{w.writing}       #{r.misaka_str}\n"
        txt.write "#{w.writing}  [#{w.writing}]        #{r.misaka_str}\n"
      end
      # voca.write "#{w.writing}       #{w.misaka_str}\n"
      # txt.write "#{w.writing}  [#{w.writing}]        #{w.misaka_str}\n"
    end

    voca.write "% NOISE\n"
    voca.write "<sp>    sp\n"
    voca.write "% NS_B\n"
    voca.write "<s>     silB\n"
    voca.write "% NS_E\n"
    voca.write "</s>    silE\n"

    ## for Fixed style grammer rules
    ## create a .grammar file
    grammar_path = path + "/#{dir_name}.grammar"
    grammar = File.open grammar_path, "w+"
    grammar.write "S:      NS_B #{dir_name} NS_E\n"
    # grammar.write "S:      NS_B #{dir_name} NOISE #{dir_name} NS_E"
    grammar.write "S:      NS_B NOISE #{dir_name} NOISE NS_E"

    grammar.close
    voca.close
    txt.close
    
    
    # Dir::rmdir path
    # p File.exists? path
  end

  def dir_name
    name + "_" + user.id.to_s
  end
=end
end

app/controllers/dictionaries_controller.rb
# -*- coding: utf-8 -*-

require "net/http"
require "uri"
require "csv"
require 'xml/libxml'

class DictionariesController < ApplicationController
  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.order :name

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dictionaries }
    end
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
    @dictionary = Dictionary.find(params[:id])
    @words = @dictionary.words
    @server = request.host_with_port

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dictionary }
    end
  end

  # GET /dictionaries/new
  # GET /dictionaries/new.json
  def new
    @dictionary = Dictionary.new
    @grammar_styles = Dictionary.grammar_style_view_list
    @rates = Dictionary.rate_view_list
    @word_groups = WordGroup.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dictionary }
    end
  end

  # GET /dictionaries/1/edit
  def edit
    @dictionary = Dictionary.find(params[:id])
    @grammar_styles = Dictionary.grammar_style_view_list
    @rates = Dictionary.rate_view_list
    @word_groups = WordGroup.all
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(params[:dictionary])

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render json: @dictionary, status: :created, location: @dictionary }
      else
        format.html { render action: "new" }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dictionaries/1
  # PUT /dictionaries/1.json
  def update
    @dictionary = Dictionary.find(params[:id])

    respond_to do |format|
      if @dictionary.update_attributes(params[:dictionary])
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary = Dictionary.find(params[:id])
    @dictionary.destroy

    respond_to do |format|
      format.html { redirect_to dictionaries_url }
      format.json { head :no_content }
    end
  end
  
  # GET /dictionaries/1/evaluate
  def evaluate

    @dictionary = Dictionary.find(params[:id])
    @recog_process = @dictionary.recog_processes.find_by_id params[:recog_process_id]
    match_count = 0
    miss_count = 0
    total_count = 0
    
    csv_path = "#{Rails.root}/sounds/robots/16k/robots_16k.csv"
    reader = CSV.open(csv_path, "r")
    reader.each do |row_ary|
      file_path = "#{Rails.root}/sounds/robots/16k/#{row_ary[0]}"
      msk_xml = post_to_msk file_path, @recog_process, @dictionary
      elements = msk_xml.find "//ELEMENT"
      result = ""
      elements.each do |elem|
        if elem.attributes['PHONE'] == "silB"
          # p "start"
        elsif elem.attributes['PHONE'] == "silE"
          # p "end"
        else
          # p elem.attributes['WORD'] + " " + elem.attributes['PHONE']
          result += elem.attributes['WORD']
        end
      end
      row_ary[1].gsub!(/\s/, "")
      
      total_count += 1
      if result == row_ary[1]
        match_count += 1
        p "match!"
      else
        miss_count += 1
        p "not match!! |#{result}| |#{row_ary[1]}|"
      end
    end
    p "total: #{total_count}, match: #{match_count}, miss: #{miss_count}"
    p "averate: #{match_count / total_count}"
  end

  # GET /dictionaries/1/auto_evaluate
  def auto_evaluate
    @dictionary = Dictionary.find(params[:id])
    @recog_process = @dictionary.recog_processes.find_by_id params[:recog_process_id]
    match_count = 0
    miss_count = 0
    total_count = 0

    @dictionary.expressions.each do |exp|
      p exp.group_str
      word_stack = []
      in_str = ""
      w_ary_stack = Array.new
      test2 exp.word_groups, 0, Array.new, w_ary_stack
      w_ary_stack.each do |w_ary|
        in_str = ""
        w_ary.each { |w| in_str += w.readings.first.kana_str }
        # p in_str
        

        in_file_path = "#{Rails.root}/lib/open_jtalk/in.txt"
        File.open(in_file_path, "w") do |f|
          f.write in_str
        end
        dic   = '/usr/local/share/open_jtalk/open_jtalk_dic_utf_8-1.05'
        f_voice = '/usr/local/share/hts_voice/mei_normal'
        outfile48 = "#{Rails.root}/lib/open_jtalk/out48.wav"
        outfile16 = "#{Rails.root}/lib/open_jtalk/out16.wav"
        outfile8 = "#{Rails.root}/lib/open_jtalk/out8.wav"
        voice = f_voice
        s = [
             "-x  #{dic}",
             "-td #{voice}/tree-dur.inf",
             "-tm #{voice}/tree-mgc.inf",
             "-tf #{voice}/tree-lf0.inf",
             "-tl #{voice}/tree-lpf.inf",
             "-md #{voice}/dur.pdf",
             "-mm #{voice}/mgc.pdf",
             "-mf #{voice}/lf0.pdf",
             "-ml #{voice}/lpf.pdf",
             "-dm #{voice}/mgc.win1",
             "-dm #{voice}/mgc.win2",
             "-dm #{voice}/mgc.win3",
             "-df #{voice}/lf0.win1",
             "-df #{voice}/lf0.win2",
             "-df #{voice}/lf0.win3",
             "-dl #{voice}/lpf.win1",
             "-ow #{outfile48}",
             "-s 48000", # sampling frequency
             "-p 240",
             "-a 0.55", # 高低？
             "-u 0.5", # 有声化・無声化？
             "-em #{voice}/tree-gv-mgc.inf",
             "-ef #{voice}/tree-gv-lf0.inf",
             "-cm #{voice}/gv-mgc.pdf",
             "-cf #{voice}/gv-lf0.pdf",
             "-jm 1.0", # 大小？
             "-jf 1.0", # 抑揚？
             "-k  #{voice}/gv-switch.inf",
             "-z 6000"
            ]
        r = s.join(" ")
        system "open_jtalk #{r} #{in_file_path}"
        system "sox --norm #{outfile48} -r 16000 #{outfile16}"
        system "sox --norm #{outfile48} -r 8000 #{outfile8}"

        msk_xml = post_to_msk outfile16, @recog_process, @dictionary
        elements = msk_xml.find "//ELEMENT"
        result = ""
        elements.each do |elem|
          if elem.attributes['PHONE'] == "silB"
            # p "start"
          elsif elem.attributes['PHONE'] == "silE"
            # p "end"
          else
            # p elem.attributes['WORD'] + " " + elem.attributes['PHONE']
            result += elem.attributes['WORD']
          end
        end
        expected = ""
        w_ary.each { |w| expected += w.writing }
        
        total_count += 1
        if result == expected
          match_count += 1
          p "match!"
        else
          miss_count += 1
          p "not match!! expected: |#{expected}|, but result is: |#{result}| "
        end
        File.delete in_file_path
        File.delete outfile48
        File.delete outfile16
        File.delete outfile8
      end

    end

    p "total: #{total_count}, match: #{match_count}, miss: #{miss_count}"
    p "averate: #{match_count.to_f / total_count}"
  end
  
  def julius_evaluate
    @dictionary = Dictionary.find(params[:id])
    @recog_process = @dictionary.recog_processes.find_by_id params[:recog_process_id]
    
    csv_path = "#{Rails.root}/sounds/robots/16k/robots_16k.csv"
    reader = CSV.open(csv_path, "r")
    reader.each do |row_ary|
      file_path = "#{Rails.root}/sounds/robots/16k/#{row_ary[0]}"
      ret_xml = post_to_julius file_path, @recog_process, @dictionary
    end
  end

private
  
  def post_to_msk(file_path, rp, dictionary)
    uri = URI.parse("http://#{rp.fqdn}/mskserver/gateway.php?username=#{dictionary.name}_#{rp.id}&password=testpass&mode=xml")
    # uri = URI.parse("http://192.168.1.156/mskserver/gateway.php?username=robots_1051294554&password=testpass&mode=xml")
    Net::HTTP.start(uri.host, uri.port) do |http|
      ## create request instance

      request = Net::HTTP::Post.new(uri.request_uri)

      ## header part
      request["user-agent"] = "Ruby/#{RUBY_VERSION} MyHttpClient"
      request.set_content_type("multipart/form-data; boundary=myboundary")
      ## following expresion is also OK
      # request["content-type"] = "multipart/form-data; boundary=myboundary"
      
      ## body part
      ## create body part with the specification of multipart/form-data
      body = ""

      # body.concat("--myboundary\r\n")
      # body.concat("content-disposition: form-data; name=\"id\";\r\n")
      # body.concat("\r\n")
      # body.concat("1\r\n")

      body.concat("--myboundary\r\n")
      body.concat("content-disposition: form-data; name=\"upfile\"; filename=\"recdata_eva5_activate.wav\"\r\n")
      body.concat("\r\n")
      File::open(file_path) { |f| body.concat(f.read + "\r\n") }

      body.concat("--myboundary--\r\n")
      request.body = body
      
      ## send
      response = http.request(request)

      # p response.body
      inxml_str = response.body
      inxml_str.gsub! "<s>", "replaced_start"
      inxml_str.gsub! "</s>", "replaced_end"
      parser = XML::Parser.string(inxml_str,
                                  :encoding => XML::Encoding::UTF_8,
                                  :options => XML::Parser::Options::NOBLANKS)
      parser.parse
    end
  end

  def get_word_stack(org_wg_ary, current_wg, stack_element_org, stack)
    if org_wg_ary.last == current_wg
      current_wg.readings.each do |r|
        clone = stack_element_org.dup
        clone << r.kana_str
        stack << clone
      end
      

    end
  end

  def test2(org_wg_ary, depth, w_ary, w_ary_stack)
    # p "depth #{depth}"
    current_wg = org_wg_ary[depth]
    current_wg.words.each do |w|
      if org_wg_ary.last == current_wg
        # p "last wg"
        clone = w_ary.dup
        clone << w
        w_ary_stack << clone
      else

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_dictionary_member_fields.html.erb
<fieldset>
  <%= f.label :word_group_id %>
  <%= f.select :word_group_id, @word_groups.collect { |wg| [wg.name, wg.id] }%>
  <%= f.check_box :_destroy %> Remove?
</fieldset>

app/views/dictionaries/_form.html.erb
<%= form_for @dictionary, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Dictionary</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :grammar_style, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :grammar_style, @grammar_styles %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :rate, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :rate, @rates %>
      </div>
    </div>
    
    <%= f.fields_for :dictionary_members do |builder| %>
      <%= render 'dictionary_member_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Add WordGroup", f, :dictionary_members %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', dictionaries_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/dictionaries/edit.html.erb
<%= render :partial => 'form' %>

app/views/dictionaries/index.html.erb
<h1>Dictionarys</h1>

<%= link_to 'New', new_dictionary_path, :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Grammar style</th>
      <th>Rate</th>
      <th>Port</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= dictionary.id %></td>
        <td><%= link_to dictionary.name, dictionary_path(dictionary) %></td>
        <td><%= dictionary.grammar_style %></td>
        <td><%= dictionary.rate %></td>
        <td>
          <% dictionary.recog_processes.each do |rp| %>
            <% if rp.status == RecogProcess::RUNNING %>
              <span class="badge badge-info"><%= rp.port %></span>
            <% else %>
              <%= rp.port %>
            <% end %>
          <% end %>
        </td>
        <td><%= dictionary.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_dictionary_path(dictionary), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', dictionary_path(dictionary), :method => :delete, :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dictionaries/new.html.erb
<%= render :partial => 'form' %>

app/views/dictionaries/show.html.erb
<script type="text/javascript">
  function loadSWF() {
  // For version detection, set to min. required Flash Player version, or 0 (or 0.0.0), for no version detection. 
  var swfVersionStr = "11.1.0";
  // To use express install, set to playerProductInstall.swf, otherwise the empty string. 
  var xiSwfUrlStr = "/assets/IkefujiPanda_release/playerProductInstall.swf";
  var flashvars = {};
  flashvars.server = "<%= @server %>";
  flashvars.dictionaryID = "<%= @dictionary.id %>";
  flashvars.dictionaryName = "<%= @dictionary.name %>";
  var params = {};
  params.quality = "high";
  params.bgcolor = "#ffffff";
  params.allowscriptaccess = "sameDomain";
  params.allowfullscreen = "true";
  var attributes = {};
  attributes.id = "IkefujiPanda";
  attributes.name = "IkefujiPanda";
  attributes.align = "middle";
  swfobject.embedSWF(
  "/assets/IkefujiPanda_release/IkefujiPanda.swf", "flashContent", 
  "100%", "100%", 
  swfVersionStr, xiSwfUrlStr, 
  flashvars, params, attributes);
  // JavaScript enabled so display the flashContent div in case it is not replaced with a swf object.
  swfobject.createCSS("#flashContent", "display:block;text-align:left;");
  }

  jQuery(function() {
    loadSWF();
  });
</script>

<h1><%= @dictionary.name %></h1>
<br />
<%= link_to "Edit", edit_dictionary_path(@dictionary), { class: 'btn btn-mini' } %>

<p>
  <b>Name: </b>
  <%= @dictionary.name %><br />
  
  <b>User: </b>
  <%= @dictionary.user.email if !@dictionary.user.blank? %><br />
  
  <b>Style: </b>
  <%= @dictionary.grammar_style %><br />

  <b>Rate: </b>
  <%= @dictionary.rate %><br />
  
  <br />
</p>

<br />
<br />

<h2>Recognition processes</h2>
<%= link_to 'New RecogProcess', new_dictionary_recog_process_path(@dictionary),
    :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>fqdn</th>
      <th>server_ip</th>
      <th>Engine type</th>
      <th>port</th>
      <th>grammar_style</th>
      <th>rate</th>
      <th>status</th>
      <th>REST</th>
    </tr>
  </thead>
  <tbody>
    <% @dictionary.recog_processes.each do |rp| %>
      <tr>
        <td><%= rp.id %></td>
        <td><%= rp.fqdn %></td>
        <td><%= rp.server_ip %></td>
        <td><%= rp.engine_type %></td>
        <td><%= rp.port %></td>
        <td><%= rp.grammar_style %></td>
        <td><%= rp.rate %></td>
        <td><%= rp.status %></td>
        <td>
          <%= link_to "Edit", edit_dictionary_recog_process_path(rp.dictionary, rp), { class: 'btn btn-mini' } %>
          <%= link_to 'Destroy', dictionary_recog_process_path(rp.dictionary, rp), :method => :delete, :class => 'btn btn-mini btn-danger' %>

        </td>
      </tr>
      <tr>
        <td colspan="9">
          <%= link_to "status", 
              status_dictionary_recog_process_path(rp.dictionary_id, rp) %> | 
          <%= link_to "register",
              register_dictionary_recog_process_path(rp.dictionary_id, rp) %> | 
          <%= link_to "start",
              start_dictionary_recog_process_path(rp.dictionary_id, rp) %> | 
          <%= link_to "stop",
              stop_dictionary_recog_process_path(rp.dictionary_id, rp) %> | 
          <%= link_to "unregister(delete)",
              unregister_dictionary_recog_process_path(rp.dictionary_id, rp) %>
          <br />
          <%= link_to "recog page",
              "http://#{rp.fqdn}/mskserver/gateway.php?username=#{@dictionary.name}_#{rp.id}&password=testpass&mode=html",
              { target: "_blank" } %>
          <% if flash[rp.id] %>
          <br />
          <%= "status msg: #{flash[rp.id]}" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<br />
<br />


<h2>Word groups</h2>
<p>
  <%= link_to 'Add word group', "#",
      :class => 'btn btn-primary' %>
</p>

<% @dictionary.word_groups.each do |wg| %>
  <h3><%= wg.name %></h3>
  
  <p>
    <%= link_to "Detail", word_group_path(wg), { class: 'btn btn-mini' } %>
    <%= link_to "Edit", edit_word_group_path(wg), { class: 'btn btn-mini' } %>
  </p>
  
  <%= render 'word_groups/word_group_table', wg: wg %>
<% end %>
<br />
<br />


<h2>Expressions</h2>

<p>
  <%= link_to "New", new_dictionary_expression_path(@dictionary), { class: 'btn btn-mini' } %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Expression</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @dictionary.expressions.each do |exp| %>
    <tr>
      <td><%= exp.id %></td>
      <td><%= exp.name %></td>
      <td>
        <!--
        <% exp.word_groups.each do |exp_wg| %>
          <%= exp_wg.name %> 
        <% end %>
        -->
        <%= exp.group_str %><br />
        <%= exp.group_str("NOISE") %>
      </td>
      <td>
        <%= link_to "Edit", edit_dictionary_expression_path(@dictionary, exp), { class: 'btn btn-mini' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />
<br />



<h2>IkefujiPanda</h2>
<div id="flashArea">
  <div id="flashContent">
    <p>
      To view this page ensure that Adobe Flash Player version 
      10.2.0 or greater is installed. 
    </p>
    <script type="text/javascript"> 
      var pageHost = ((document.location.protocol == "https:") ? "https://" : "http://"); 
      document.write("<a href='http://www.adobe.com/go/getflashplayer'><img src='" + pageHost + "www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a>" ); 
    </script> 
  </div>
</div>
<br />
<br />

<h2>Evaluation</h2>
<%= form_tag auto_evaluate_dictionary_path(@dictionary), 
    { :class => 'form-horizontal', :method => :get } do |f| %>

  <%= select_tag :recog_process_id,
      options_from_collection_for_select(@dictionary.recog_processes, "id", "fqdn")
      %>
  <%= submit_tag 'Auto Evaluate', :class => 'btn btn-primary' %>
<% end %>

<%= form_tag evaluate_dictionary_path(@dictionary), 
    { :class => 'form-horizontal', :method => :get } do |f| %>
  
  <%= select_tag :recog_process_id,
      options_from_collection_for_select(@dictionary.recog_processes, "id", "fqdn")
      %>
  <%= submit_tag 'Evaluate', :class => 'btn btn-primary' %>
<% end %>

<%= form_tag julius_evaluate_dictionary_path(@dictionary), 
    { :class => 'form-horizontal', :method => :get } do |f| %>
  
  <%= select_tag :recog_process_id,
      options_from_collection_for_select(@dictionary.recog_processes, "id", "fqdn")
      %>
  <%= submit_tag 'Julius evaluate', :class => 'btn btn-primary' %>
<% end %>



<div class="form-actions">
  <%= link_to 'Back', dictionaries_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_dictionary_path(@dictionary), :class => 'btn' %>
  <%= link_to 'Delete', dictionary_path(@dictionary), :method => 'delete', :class => 'btn btn-danger' %>
</div>