config/routes.rb
Ikefuji::Application.routes.draw do

  devise_for :users

  resources :dictionaries do 
    member do 
      get :evaluate
      get :auto_evaluate
      get :julius_evaluate
      get :julius_auto_evaluate
    end
    resources :recog_processes do 
      member do 
        get :status
        get :register
        get :start
        get :stop
        get :unregister
      end
    end
    resources :expressions
  end

  resources :readings
  resources :word_groups
  resources :words

  root :to => 'dictionaries#index'

end

app/models/word.rb
# -*- coding: utf-8 -*-

class Word < ActiveRecord::Base
  include Translate

  attr_accessible :writing, 
  # :word_associations_attributes,
  :readings_attributes

  belongs_to :dictionary
  has_many :word_associations, dependent: :destroy
  has_many :readings, through: :word_associations
  has_many :users, through: :word_associations

  # accepts_nested_attributes_for :word_associations
  accepts_nested_attributes_for :readings, allow_destroy: true


  before_validation :insert_proper_readings

  def kana_str_list
    readings.map { |r| r.kana_str }
  end

  def word_association(reading)
    word_associations.find { |wa| wa.reading == reading }
  end

  # def insert_proper_readings
  #   # p readings
  #   self.readings.each_with_index do |r, index|
  #     ret = Reading.where(kana_str: r.kana_str)
  #     # p "After index:#{index}, length:#{ret.length}"

  #     if ret.length != 0
  #       self.readings[index] = ret.first
  #     end
  #   end
  #   p readings
  # end

  def add_readings(readings_attributes)
    readings_attributes.each do |key, value|
      # ret = Reading.where(kana_str: value[:kana_str])
      ret = Reading.new({ kana_str: value[:kana_str] })#  if ret == nil
      self.readings << ret
    end
  end

  def insert_proper_readings
    # p readings
    self.readings.each_with_index do |r, index|
      # p r
      ret = Reading.where(kana_str: r.kana_str)
      # p "After index:#{index}, length:#{ret.length}"
      if ret.length != 0
        # self.readings[index] = ret.first
        ret_index = self.word_associations.index { |item| item.reading == ret.first }
        if ret_index.nil?
          self.word_associations.new(word: self, reading: ret.first)
          self.readings.delete r
        end
      end
    end
    # p readings
  end


  # def misaka_str
  #   Word.translate self.reading
  # end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    # @dictionary = Dictionary.find params[:dictionary_id]
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: 
        @word.to_json(include: { 
                        word_associations: {
                          only: [ :id ],
                          include: {
                            reading: { only: [ :id, :kana_str ] }
                          }
                        }
                      }) }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    # p params
    @word = Word.new
    @word.readings << Reading.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    # p params
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    # p params
    @word = Word.find_by_writing params[:word][:writing]
    @word = Word.new({ writing: params[:word][:writing] }) if @word == nil
    @word.add_readings params[:word][:readings_attributes]
    
    respond_to do |format|
      if @word.save
        format.html { redirect_to words_path,
          notice: "Word(ID:#{@word.id} '#{@word.writing}') was successfully created."
        }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    # p params
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to words_path, 
          notice: "Word(ID:#{@word.id} '#{@word.writing}') was successfully updated."
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    # p params
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_path, 
        notice: "Word(ID:#{@word.id} '#{@word.writing}') was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for @word, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Word</legend>

    <div class="control-group">
      <%= f.label :writing, :class => 'control-label' %>
      <div class="controls">
        <!-- <%= f.check_box :writing %> -->
        <%= f.text_field :writing, :class => 'text_field' %>
      </div>
    </div>

    <%= f.fields_for :readings do |rbuilder| %>
      <%= render 'reading_fields', f: rbuilder %>
    <% end %>

    <%= link_to_add_fields "Add Reading", f, :readings %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', words_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/words/_reading_fields.html.erb
<fieldset>
  <%= f.text_field :kana_str %>
  <%= f.check_box :_destroy %> Remove?
</fieldset>

app/views/words/edit.html.erb
<%= render :partial => 'form' %>

app/views/words/index.html.erb
<h1>Words</h1>

<%=
link_to 'New', new_word_path, :class => 'btn btn-primary' 
%>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Writing</th>
      <th>Readings</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.id %></td>
        <td><%= word.writing %></td>
        <td>
          <% word.readings.each do |r| %>
            <%= "#{r.kana_str} (ID:#{r.id})" %><br />
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
          edit_word_path(word), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          word_path(word),
          :method => :delete,
          :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/words/new.html.erb
<%= render :partial => 'form' %>

app/views/words/show.html.erb
<h1>/Word</h1>

<p>
  <b>Dictionary</b><br>
  <%= @word.dictionary_id %>
</p>

<p>
  <b>Writing</b><br>
  <%= @word.writing %>
</p>

<p>
  <b>Reading</b><br>
  <%= @word.reading %>
</p>

<div class="form-actions">
  <%= link_to 'Back', dictionary_words_path(@dictionary), :class => 'btn'  %>
  <%= link_to 'Edit', edit_dictionary_word_path(@word), :class => 'btn' %>
  <%= link_to 'Delete', dictionary_word_path(@word), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>