config/routes.rb
Ikefuji::Application.routes.draw do

  devise_for :users

  resources :dictionaries do 
    member do 
      get :evaluate
      get :auto_evaluate
      get :julius_evaluate
      get :julius_auto_evaluate
    end
    resources :recog_processes do 
      member do 
        get :status
        get :register
        get :start
        get :stop
        get :unregister
      end
    end
    resources :expressions
  end

  resources :readings
  resources :word_groups
  resources :words

  root :to => 'dictionaries#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ikefuji</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application" %>
    
    <!-- Le javascript -->
    <%= javascript_include_tag "application" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Ikefuji", root_path, { class: "brand" }%>

          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Dictionaries", dictionaries_path  %></li>
              <li><%= link_to "Word groups", word_groups_path  %></li>
              <li><%= link_to "Words", words_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
       <% flash.each do |name, msg| %>
         <% if name == :notice %>
           <div class="alert alert-success">
             <a class="close" data-dismiss="alert">x</a>
             <%= msg  %>
           </div>
         <% end %>
         <% if name == :error %>
           <div class="alert alert-error">
             <a class="close" data-dismiss="alert">x</a>
             <%= msg  %>
           </div>
         <% end %>
       <% end %>
       
      <div class="row-fluid">
        <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Chapek 2012</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>